name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build chesszebra/composer:7.2
      run: docker build . --file src/7.2/Dockerfile --tag chesszebra/composer:7.2
    - name: Build chesszebra/composer:latest
      run: docker build . --file src/7.2/Dockerfile --tag chesszebra/composer:latest
